FROM ubuntu:24.04
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
  build-essential cmake ninja-build git python3-pip \
  clang clang-tidy clang-format cppcheck gcovr lcov \
  doxygen graphviz \
  gcc-arm-none-eabi gdb-multiarch \
  && rm -rf /var/lib/apt/lists/*
WORKDIR /workspace

