name: Wiki Sync
on:
  push:
    branches: [ main ]
    paths:
      - 'docs/wiki/**'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Publish wiki pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash scripts/publish_wiki.sh

